### ISSUE TITLE
Panic with error "not implemented: No support to dereference ......"

### ISSUE THREAD

**Issue by xli** [matusf/openapi-fuzzer#7]
OpenAPI specification file: https://github.com/diem/diem/blob/main/api/doc/openapi.yaml

Error:
```
thread 'main' panicked at 'not implemented: No support to dereference #/components/schemas/MoveAbility.', /Users/ilx/.cargo/registry/src/github.com-1ecc6299db9ec823/openapi_utils-0.2.1/src/reference.rs:69:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looked into the dereferenced schema, looks like some references inside array#items are not dereferenced.

**Comment by matusf** [comment]
Thanks for the report. I looks like a bug in a [depending crate](https://github.com/JordiPolo/oas_proxy/tree/master/openapi_utils), I'll look into it. If you had some minimal example where it fails, it'd be great.

**Comment by xvilo** [comment]
I'm also experiencing this! We have the following markup

```
# openapi.yml
paths:
  /api/v1/health:
    $ref: 'components/internal.yml#/endpoints/getHealth'
```

This references a the file `components/internal.yml` relative to `openapi.yml` file location. It has the following contents
```yaml
endpoints:
  getHealth:
    get:
      description: Gets health check.
      operationId: getHealth
      [....]
```

which will give
```
thread 'main' panicked at 'not implemented: No support to dereference components/internal.yml#/endpoints/getHealth.'
```

**Comment by xvilo** [comment]
I'm also experiencing this! We have the following markup

```
# openapi.yml
paths:
  /api/v1/health:
    $ref: 'components/internal.yml#/endpoints/getHealth'
```

This references a the file `components/internal.yml` relative to `openapi.yml` file location. It has the following contents
```yaml
endpoints:
  getHealth:
    get:
      description: Gets health check.
      operationId: getHealth
      [....]
```

which will give
```
thread 'main' panicked at 'not implemented: No support to dereference components/internal.yml#/endpoints/getHealth.'
```

Is this enough info for you @matusf?
